name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - Vivify/**
    - Vivify.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.38.0 ]
    uses: Aeroluna/beat-saber-workflows/.github/workflows/build-version-release.yml@master
    with:
      project-path: Vivify/Vivify.csproj
      game-version: ${{ matrix.game-version }}
      additional-sources: '{"Heck": "Aeroluna/Heck", "CustomJSONData": "Aeroluna/CustomJSONData"}'
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/beat-saber-workflows/.github/workflows/create-release-from-project.yml@master
    with:
      project-path: Vivify/Vivify.csproj
    secrets: inherit
