name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - Vivify/**
    - Vivify.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.39.1, 1.40.3 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: Vivify/Vivify.csproj
      game-version: ${{ matrix.game-version }}
      additional-sources: '["Aeroluna/Heck", "Aeroluna/CustomJSONData"]'
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-project.yml@main
    with:
      project-path: Vivify/Vivify.csproj
    secrets: inherit
